[package]
name = "simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
derive_more = "2.0.1"
env_logger = "0.11.8"
log = "0.4.28"
tokio = { version = "1", features = ["fs"] }
serde = "1"
toml = "0.9"
url = { version = "2.5.7", features = ["serde"] }
anyhow = "1"
typed-builder = "0.23.2"
ordered-float = { version = "5", features = ["serde"] }
