bank_user_id = "bank"
resources = [""]
[costs.trust]
money = 2
resources = {}

[costs.base]
money = 12
resources = {}

[costs.unit]
money = 2
resources = {}

[server]

[persistence]
uri = "mongodb://localhost:27017"
database = "simulation"
interval_seconds = 30

[env]
credit_exchange_url = "http://127.0.0.1:18080"

[combat]
combat_tick_interval_seconds = 1.5
production_interval_seconds = 20
movement_interval_seconds = 60
movement_step = 1.0
base_destruction_threshold = 5
trust_destruction_threshold = 4

[combat.loot_factors]
money = 0.5
resources = {}

[[bloc]]
name = "west"
chance = 100
military_expense = 0.1

[[bloc]]
name = "east"
chance = 100
military_expense = 0.1

[[zone]]
name = "zone_w"
bloc = "west"

[[zone]]
name = "zone_e"
bloc = "east"

[[placement]]
id = "placement_1w"
zone = "zone_w"
position = { x = 23.2, y = 29.1 }

[[placement]]
id = "placement_2w"
zone = "zone_w"
position = { x = 25.2, y = 29.1 }

[[placement]]
id = "placement_1e"
zone = "zone_e"
position = { x = 29.2, y = 29.1 }
